export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';
export const USER_ROLES_REPOSITORY = 'USER_ROLES_REPOSITORY';
export const SEQUELIZE = 'SEQUELIZE';
export const BLOG_REPOSITORY = 'BLOG_REPOSITORY';